# Generated by Django 6.0.4 on 2026-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='proposal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='timeline',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='writing_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksubmission',
            name='content',
            field=models.TextField(),
        ),
    ]
